on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Build project
        run: vite build
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
